apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  repositories: |
    - name: k8s-gitops-workshop
      url: git@github.com:SCGWEDOtech/k8s-gitops-workshop.git
      sshPrivateKeySecret:
        name: repository-secret
        key: k8sWorkshopDeployKey
